version: '3.8'
services:
  db:
    image: postgres:18
    container_name: aura-postgres
    environment:
      POSTGRES_USER: aura_user
      POSTGRES_PASSWORD: aura_password
      POSTGRES_DB: auradb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: