spring.application.name=suite
#server.servlet.context-path=/aura

# DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5332/auradb
spring.datasource.username=aura_user
spring.datasource.password=aura_password

# JPA / Hibernate logic
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# 1. HikariCP Connection Pool Tuning
# Increase the pool if you have many concurrent workers
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=AuraHikariPool

# 2. Hibernate/JPA Batching (Crucial for saving 70M results)
# This tells Hibernate to send 500 inserts in ONE network call instead of 500
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# 3. Async Task Execution (If using @Async)
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=50
spring.task.execution.pool.queue-capacity=10000